server:
  port: 9716
jasypt:
  encryptor:
    # 加密密码，建议使用环境变量或启动参数
    password: my_password
    # 默认加密算法AES256，可省略
    algorithm: PBEWithHMACSHA512AndAES_256
encode:
  msg: ENC(JNuYlUXofUCnuFWbyBhe6XaLfCja1ScLzhLkBZhauDblrOBwGrOhjaqMOal6nR8Q68zTmfvqWUcVQoCo79HwBgSQ3rdAmEoNoKrgJqPHAiEuds56/M+fp0k2f+b+mJGo)