server:
  port: 9716

spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    # 数据库（默认为0号库）
    database: 1
    # 密码（默认空），操作redis需要使用的密码
    password: test
    # 端口号
    #    port: 6379
    #连接超时时间（毫秒）
    timeout: 10000ms
    sentinel:
      master: mymaster
      nodes:
        - 127.0.0.1:26379
        - 127.0.0.1:26380
        - 127.0.0.1:26381
      # 操作sentinel时需要提供的密码
      password: sentinel
    # 使用lettuce配置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
